from __future__ import annotations

import mimetypes
import posixpath
from dataclasses import dataclass
from pathlib import PurePosixPath
from urllib.parse import quote, unquote, urlparse, urlunparse


class AliyunOSSError(RuntimeError):
    """Normalized failure for server-generated OSS artifacts."""


@dataclass(frozen=True)
class AliyunOSSConfig:
    endpoint: str
    bucket: str
    prefix: str
    access_key_id: str
    access_key_secret: str
    security_token: str = ""
    signed_url_ttl_seconds: int = 86400


class AliyunOSSStore:
    """Store generated TTS clips and media outputs in a private OSS bucket.

    This service-side store is independent from the existing desktop upload flow.
    The desktop still owns source uploads, STS issuance, resume state, and subtitle
    removal. This class only writes artifacts generated by CineFlow workers.
    """

    def __init__(self, config: AliyunOSSConfig, *, bucket_client=None) -> None:
        self.config = config
        self._bucket_client = bucket_client

    @property
    def configured(self) -> bool:
        return bool(
            self.config.endpoint.strip()
            and self.config.bucket.strip()
            and self.config.access_key_id.strip()
            and self.config.access_key_secret.strip()
        )

    @property
    def endpoint_host(self) -> str:
        parsed = urlparse(self._normalized_endpoint())
        return parsed.netloc

    def _normalized_endpoint(self) -> str:
        value = self.config.endpoint.strip().rstrip("/")
        if not value:
            return ""
        return value if "://" in value else f"https://{value}"

    def _bucket(self):
        if self._bucket_client is not None:
            return self._bucket_client
        if not self.configured:
            raise AliyunOSSError("Alibaba OSS artifact-store configuration is incomplete")
        try:
            import oss2
        except ImportError as exc:  # pragma: no cover - production dependency
            raise AliyunOSSError(
                "install the 'aliyun' optional dependencies to write OSS artifacts"
            ) from exc

        if self.config.security_token.strip():
            auth = oss2.StsAuth(
                self.config.access_key_id.strip(),
                self.config.access_key_secret.strip(),
                self.config.security_token.strip(),
            )
        else:
            auth = oss2.Auth(
                self.config.access_key_id.strip(),
                self.config.access_key_secret.strip(),
            )
        self._bucket_client = oss2.Bucket(
            auth,
            self._normalized_endpoint(),
            self.config.bucket.strip(),
        )
        return self._bucket_client

    def key(self, *parts: str) -> str:
        cleaned = [
            str(PurePosixPath(part.strip().lstrip("/")))
            for part in parts
            if str(part or "").strip()
        ]
        prefix = str(PurePosixPath(self.config.prefix.strip().strip("/")))
        if prefix and prefix != ".":
            cleaned.insert(0, prefix)
        return posixpath.normpath("/".join(cleaned)).lstrip("/")

    def canonical_url(self, object_key: str) -> str:
        if not self.config.bucket.strip() or not self.endpoint_host:
            raise AliyunOSSError("Alibaba OSS endpoint or bucket is missing")
        encoded = quote(object_key.lstrip("/"), safe="/~-._")
        return f"https://{self.config.bucket.strip()}.{self.endpoint_host}/{encoded}"

    def oss_uri(self, object_key: str) -> str:
        return f"oss://{self.config.bucket.strip()}/{object_key.lstrip('/')}"

    def put_bytes(
        self,
        object_key: str,
        content: bytes,
        *,
        content_type: str = "",
    ) -> None:
        headers = {}
        guessed = content_type or mimetypes.guess_type(object_key)[0] or ""
        if guessed:
            headers["Content-Type"] = guessed
        try:
            result = self._bucket().put_object(object_key, content, headers=headers)
        except Exception as exc:
            raise AliyunOSSError(f"failed to upload OSS object {object_key}: {exc}") from exc
        status = int(getattr(result, "status", 200) or 200)
        if status < 200 or status >= 300:
            raise AliyunOSSError(
                f"failed to upload OSS object {object_key}: HTTP {status}"
            )

    def signed_url(self, object_key: str) -> str:
        try:
            return str(
                self._bucket().sign_url(
                    "GET",
                    object_key,
                    int(self.config.signed_url_ttl_seconds),
                    slash_safe=True,
                )
            )
        except TypeError:
            # Older oss2 releases do not expose slash_safe.
            try:
                return str(
                    self._bucket().sign_url(
                        "GET",
                        object_key,
                        int(self.config.signed_url_ttl_seconds),
                    )
                )
            except Exception as exc:
                raise AliyunOSSError(
                    f"failed to sign OSS object {object_key}: {exc}"
                ) from exc
        except Exception as exc:
            raise AliyunOSSError(
                f"failed to sign OSS object {object_key}: {exc}"
            ) from exc

    def object_key_from_url(self, value: str) -> str | None:
        parsed = urlparse(str(value or ""))
        if parsed.scheme == "oss" and parsed.netloc == self.config.bucket.strip():
            return unquote(parsed.path.lstrip("/"))
        if parsed.scheme not in {"http", "https"}:
            return None
        expected_host = f"{self.config.bucket.strip()}.{self.endpoint_host}".lower()
        if parsed.netloc.split(":", 1)[0].lower() != expected_host:
            return None
        return unquote(parsed.path.lstrip("/"))

    def sign_if_owned(self, value: str) -> str:
        object_key = self.object_key_from_url(value)
        return self.signed_url(object_key) if object_key else value

    @staticmethod
    def canonicalize_oss_input(value: str) -> str:
        """Strip a signed-query string while preserving an Alibaba OSS URL.

        IMS consumes source assets with the caller's Alibaba account permissions.
        Removing an expiring query avoids a long job failing after a source URL
        signature expires. Non-OSS URLs remain unchanged and will be rejected by
        IMS instead of being silently rewritten.
        """

        parsed = urlparse(str(value or ""))
        host = parsed.netloc.split(":", 1)[0].lower()
        is_aliyun_oss = host.endswith(".aliyuncs.com") and ".oss-" in host
        if parsed.scheme in {"http", "https"} and is_aliyun_oss:
            return urlunparse((parsed.scheme, parsed.netloc, parsed.path, "", "", ""))
        return str(value)
