# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt

from videotrans.configure.config import tr
from videotrans.util import tools


class Ui_azurettsform(object):
    def setupUi(self, azurettsform):
        self.has_done = False
        azurettsform.setObjectName("azurettsform")
        azurettsform.setWindowModality(QtCore.Qt.NonModal)
        azurettsform.resize(440, 390)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(azurettsform.sizePolicy().hasHeightForWidth())
        azurettsform.setSizePolicy(sizePolicy)
        azurettsform.setMaximumSize(QtCore.QSize(440, 390))

        self.verticalLayout = QtWidgets.QVBoxLayout(azurettsform)
        self.verticalLayout.setObjectName("verticalLayout")

        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(azurettsform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.speech_region = QtWidgets.QLineEdit(azurettsform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speech_region.sizePolicy().hasHeightForWidth())
        self.speech_region.setSizePolicy(sizePolicy)
        self.speech_region.setMinimumSize(QtCore.QSize(210, 35))
        self.speech_region.setObjectName("speech_region")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.speech_region)

        self.formLayout_22 = QtWidgets.QFormLayout()
        self.formLayout_22.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_22.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_22.setObjectName("formLayout_22")
        self.label22 = QtWidgets.QLabel(azurettsform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label22.sizePolicy().hasHeightForWidth())
        self.label22.setSizePolicy(sizePolicy)
        self.label22.setMinimumSize(QtCore.QSize(100, 35))
        self.label22.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label22.setObjectName("label22")
        self.formLayout_22.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label22)
        self.speech_key = QtWidgets.QLineEdit(azurettsform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speech_key.sizePolicy().hasHeightForWidth())
        self.speech_key.setSizePolicy(sizePolicy)
        self.speech_key.setMinimumSize(QtCore.QSize(210, 35))
        self.speech_key.setEchoMode(QtWidgets.QLineEdit.Password)
        self.speech_key.setObjectName("speech_key")
        self.key_widget = QtWidgets.QWidget(azurettsform)
        self.key_layout = QtWidgets.QHBoxLayout(self.key_widget)
        self.key_layout.setContentsMargins(0, 0, 0, 0)
        self.key_layout.addWidget(self.speech_key)
        self.show_key = QtWidgets.QToolButton(self.key_widget)
        self.show_key.setCheckable(True)
        self.show_key.setMinimumSize(QtCore.QSize(45, 35))
        self.show_key.setObjectName("show_key")
        self.key_layout.addWidget(self.show_key)
        self.formLayout_22.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.key_widget)

        self.verticalLayout.addLayout(self.formLayout_22)

        self.formLayout_222 = QtWidgets.QFormLayout()
        self.formLayout_222.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_222.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_222.setObjectName("formLayout_222")

        self.label222 = QtWidgets.QLabel(azurettsform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label222.sizePolicy().hasHeightForWidth())
        self.label222.setSizePolicy(sizePolicy)
        self.label222.setMinimumSize(QtCore.QSize(100, 35))
        self.label222.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label222.setObjectName("label222")
        self.formLayout_222.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label222)

        self.azuretts_area = QtWidgets.QComboBox(azurettsform)

        self.azuretts_area.setObjectName("azuretts_area")
        self.azuretts_area.addItems([
            "EastAsia",
            "SoutheastAsia",
            "AustraliaEast",
            "AustraliaSoutheast",
            "BrazilSouth",
            "CanadaCentral",
            "CanadaEast",
            "WestEurope",
            "NorthEurope",
            "CentralIndia",
            "SouthIndia",
            "WestIndia",
            "JapanEast",
            "JapanWest",
            "KoreaCentral",
            "KoreaSouth",
            "UkWest",
            "UkSouth",
            "NorthCentralUs",
            "EastUs",
            "WestUs2",
            "WestUs3",
            "SouthCentralUs",
            "CentralUs",
            "EastUs2",
            "WestUs",
            "WestCentralUs",
            "GermanyCentral",
            "GermanyNortheast",
            "ChinaNorth",
            "ChinaEast",
            "USGovArizona",
            "USGovTexas",
            "USGovIowa",
            "USGovVirginia",
            "USDoDCentral",
            "USDoDEast"
        ])

        self.azuretts_area.setMinimumSize(QtCore.QSize(210, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        self.azuretts_area.setSizePolicy(sizePolicy)

        self.formLayout_222.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.azuretts_area)

        self.verticalLayout.addLayout(self.formLayout_222)
        self.verticalLayout.addLayout(self.formLayout_2)

        self.azure_runtime_form = QtWidgets.QFormLayout()
        self.azure_runtime_form.setObjectName("azure_runtime_form")
        self.concurrency_label = QtWidgets.QLabel(azurettsform)
        self.concurrency_label.setMinimumSize(QtCore.QSize(100, 35))
        self.azure_tts_concurrency = QtWidgets.QSpinBox(azurettsform)
        self.azure_tts_concurrency.setRange(1, 10)
        self.azure_tts_concurrency.setValue(5)
        self.azure_tts_concurrency.setMinimumHeight(35)
        self.azure_runtime_form.addRow(self.concurrency_label, self.azure_tts_concurrency)

        self.wait_label = QtWidgets.QLabel(azurettsform)
        self.wait_label.setMinimumSize(QtCore.QSize(100, 35))
        self.azure_tts_wait = QtWidgets.QDoubleSpinBox(azurettsform)
        self.azure_tts_wait.setRange(0.0, 5.0)
        self.azure_tts_wait.setDecimals(1)
        self.azure_tts_wait.setSingleStep(0.1)
        self.azure_tts_wait.setSuffix(" s")
        self.azure_tts_wait.setValue(0.0)
        self.azure_tts_wait.setMinimumHeight(35)
        self.azure_runtime_form.addRow(self.wait_label, self.azure_tts_wait)

        self.adaptive_label = QtWidgets.QLabel(azurettsform)
        self.adaptive_label.setMinimumSize(QtCore.QSize(100, 35))
        self.azure_tts_adaptive = QtWidgets.QCheckBox(azurettsform)
        self.azure_tts_adaptive.setChecked(True)
        self.azure_runtime_form.addRow(self.adaptive_label, self.azure_tts_adaptive)
        self.verticalLayout.addLayout(self.azure_runtime_form)

        self.save = QtWidgets.QPushButton(azurettsform)
        self.save.setMinimumSize(QtCore.QSize(0, 35))
        self.save.setObjectName("save")

        self.test = QtWidgets.QPushButton(azurettsform)
        self.test.setMinimumSize(QtCore.QSize(0, 35))
        self.test.setObjectName("test")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/azuretts'))

        hv = QtWidgets.QHBoxLayout()
        hv.addWidget(self.save)
        hv.addWidget(self.test)
        hv.addWidget(help_btn)

        self.verticalLayout.addLayout(hv)

        self.retranslateUi(azurettsform)
        QtCore.QMetaObject.connectSlotsByName(azurettsform)

    def retranslateUi(self, azurettsform):
        azurettsform.setWindowTitle("AzureTTS")
        self.label.setText(tr("Your SPEECH REGION"))
        self.label22.setText(tr("SPEECH_KEY"))
        self.label222.setText(tr("REGION"))
        self.show_key.setText("显示")
        self.concurrency_label.setText("最大并发请求数")
        self.wait_label.setText("请求间隔")
        self.adaptive_label.setText("动态保护")
        self.azure_tts_adaptive.setText("超时/限流时自动降低并发")
        self.save.setText(tr("Save"))
        self.test.setText(tr("Test"))
